# Generated by Django 5.2 on 2025-04-17 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TASKMASTERAPP', '0004_feedback_is_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10, null=True),
        ),
    ]
