# Generated by Django 5.2 on 2025-04-17 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TASKMASTERAPP', '0006_customuser_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='social',
            field=models.URLField(blank=True, null=True),
        ),
    ]
